sudo: required
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
script:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- echo $REPO:$TAG
- IMAGE_NAME=$REPO:$TAG ./hooks/build
- docker run --name $NAME -d $REPO:$TAG
- docker ps -a
- sleep 5
- docker logs $NAME
- docker exec $NAME pgrep rsyslogd
- docker exec $NAME pgrep fcron
- docker rm -f $NAME
- docker run --name $NAME -e DISABLE_SYSLOG=TRUE -d $REPO:$TAG
- docker ps -a
- sleep 5
- docker exec $NAME ps aux | grep -v rsyslogd 
- docker exec $NAME ps aux | grep -v "/usr/sbin/fcron"
after_script:
- docker rm -f $NAME
env:
  global:
  - NAME=baseimage-alpine
  - REPO=ajoergensen/$NAME
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
